
const DECKS = {
  open: [
    "If you could master any skill overnight, what would it be?",
    "What's a small thing that instantly puts you in a good mood?",
    "What's the best meal you've ever eaten, and where were you?",
    "Aside from Jesus, which Biblical character are you most looking forward to meeting in heaven and why?",
    "What's a hobby you'd love to try if money and time weren't an issue?",
    "If your life had a title right now, what would it be?",
    "What's a food you refused to eat as a kid but love now?",
    "What was the last song you sang in your shower concert?",
    "What's the best compliment you've ever received?",
    "If you could have dinner with anyone from history, who would it be?",
    "What's a movie or show you could watch on repeat and never get tired of?",
    "What's something you're weirdly good at?",
    "If you could live in any city in the world for a year, where would you go?",
    "What's the last thing that made you laugh until you cried?",
    "What's a tradition from your childhood you hope to carry on?",
    "What's the best gift you've ever given someone? And what's the best gift you've ever received?",
    "What's a place you've never been but really want to visit?",
    "What's your favorite way to unwind after a long week?",
    "If you could add one holiday to the calendar, what would it celebrate?",
    "What's something you learned the hard way?",
    "What's a smell that instantly brings back a memory for you?",
    "What's the most spontaneous thing you've ever done?",
    "What's a skill your parents taught you that you still use?",
    "If you could relive one day from your past, which would you pick?",
    "What's a book or podcast that's stuck with you?",
    "If you could be handed any job for a day, what would you choose?",
    "What's something on your bucket list that has nothing to do with travel?",
    "What's a nickname you've had, and how did you get it?",
    "If you could instantly fix one small annoyance in daily life, what would it be?",
    "What's your favorite thing about the town or city you live in now?",
    "What's a childhood game you wish adults still played?",
    "If you could send one text to your teenage self, what would it say?",
    "What's the best piece of advice you've ever received?",
    "What's something that always makes you feel like a kid again?",
    "If you were a kitchen appliance, which one would you be and why?",
    "What's your favorite way to spend a rainy day?",
    "If you and Jesus hosted a podcast, who would your first guest be and why?",
    "Which cartoon were you obsessed with as a kid?",
    "If you could only keep one app on your phone, which would it be?",
    "What's a compliment you give often?",
    "What's the last thing you got excited about?",
    "If you could instantly learn any language, which would you choose?",
    "What's something about you that surprises people when they first learn it?",
    "What's your favorite thing to do with your hands — cooking, building, fixing, creating?",
    "Turn to the person to your left and describe their personality using three words.",
    "What's a habit you would like to pick? And what's a habit you would like to drop?",
    "If you could do something bold just once with zero risk, what would you do?"
  ],
  uncover: [
    "What's something this month that's helped you grow mentally, emotionally, or spiritually?",
    "Where is comparison affecting your life right now?",
    "Do you have someone in your life you can be completely honest with about what you're going through?",
    "If Jesus asked you right now, \"What do you want me to do for you?\" How would you answer?",
    "What's a season of life you're grateful is over, and what did it teach you?",
    "What's a fear you've had to work through in the last few years?",
    "Who is someone who saw potential in you before you saw it in yourself?",
    "What's a relationship in your life that needs more attention right now?",
    "What's something you needed to hear as a kid that you never got to hear?",
    "What's a decision you made that changed the direction of your life?",
    "What's something you're proud of that no one applauded you for?",
    "When was the last time you felt truly known by someone?",
    "What does it look like when you're not okay — and who usually notices first?",
    "What's something you wish people asked you more often?",
    "Who has shaped your faith the most, and how?",
    "What's something about adulthood nobody warned you about?",
    "In what moment did you feel closest to God this year?",
    "What's something you've had to grieve that isn't death — a dream, a season, a relationship?",
    "What does it look like for you to feel loved well?",
    "What's a question you're afraid to ask God?",
    "What's a friendship that changed the course of your life?",
    "What's something you do to cope with stress that you'd like to replace with something healthier?",
    "What's an area where you feel like you're just going through the motions?",
    "How has your family shaped the way you see relationships?",
    "What's something you needed to let go of, and how did you find the courage?",
    "What's a time you felt God's provision in a way you couldn't explain?",
    "What's a part of yourself you're still trying to understand?",
    "What's a wound from your past that you're still healing from?",
    "What's something you wish you had more patience for — in yourself or others?",
    "What's a risk you took that you're glad you took, even though it was scary?",
    "What did you recently have to surrender to God? What did that look like?",
    "What's something you're hoping this next year looks different from the last?",
    "What's something you're afraid to want?",
    "What's a way your view of God has changed as you've gotten older?",
    "What's something you've prayed for so long you've almost stopped expecting an answer?"
  ],
  reveal: [
    "What's something you prayed for in one season that you wouldn't pray for now?",
    "What's the loneliest you've ever felt, and what got you through it?",
    "What's the closest you've come to walking away from your faith?",
    "What's something you feel like God is asking you to give up?",
    "What's a moment you felt completely unworthy of love, and what happened next?",
    "What's the hardest truth you've had to accept about someone you love?",
    "What's a promise from God you're struggling to believe right now?",
    "What's the most honest prayer you've prayed recently?",
    "What's the hardest thing you've ever had to forgive?",
    "What's a side of you that most people never get to see?"
  ],
  wild: [
    "Share a Scripture that has meant something to you lately, even just a phrase.",
    "Pause the game for two minutes and let anyone share something on their heart, no pressure.",
    "Ask someone in the group a follow-up question about something they shared earlier tonight."
  ]
};
DECKS.mix = [].concat(DECKS.open, DECKS.uncover, DECKS.reveal, DECKS.wild);
const LABELS = { open: 'Open', uncover: 'Uncover', reveal: 'Reveal', wild: 'Wildcard', mix: 'Mix All' };